/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData car_page___location = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_page___makfula = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_page___share = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_page___slindr = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home___ad1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home___ad2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home___ad3 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home___ad4 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home___menu = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home___notification_ = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home___search = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___about = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___contact = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___fav = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___home = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___partner = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___q = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___signout = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___sitting = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu___user = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData partner___add = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData partner___upload = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_page___edit = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sing_in_partner = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_page___cancel = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_page___pay = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_page___book = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_page___call = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_page___chat_by_whatsapp = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_page___fav = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
